---
VirtualMachine:
  #Internal IP e.g. "172.23.42.42"
  ip: 172.23.42.78
  # CPU cores
  cpus: 2
  # MB RAM
  memory: 4092
  # Start a with a window from the Virtualbox
  gui: false
  # Fully qualified domain name e.g. project.name.dev.domain.com
  domain: lgburg.dev
  # Alias domains separated by space
  # aliases: static.frank-original-modx.dev
  #Apt proxy setting for a local mirror or  e.g. http://10.50.101.2:3142
  aptProxy:
  # To get a IP in your local network to make the VM accessible from other devices you need a network bridge
  networkBridge: false
  # Puppet debug and verbose for more information
  puppetDebug: false
  # Virtualbox group (works only without open Virtualbox manager)
  group: /vagrant/gitbug

Mount:
  # Local folder
  from: www